/**
 * The Worker entry point.
 *
 * A Durable Object class has to be exported from the same script Wrangler
 * deploys, and `.open-next/worker.js` is generated by `opennextjs-cloudflare
 * build` on every run — editing it would be overwritten immediately. So
 * wrangler.jsonc points `main` here instead, and this file re-exports the
 * generated Worker unchanged and adds what OpenNext knows nothing about.
 *
 * `export *` does not carry a default export, which is why the default is
 * assembled below. The wildcard matters too: OpenNext exports its own Durable
 * Objects (DOQueueHandler, DOShardedTagCache, BucketCachePurge), and dropping
 * them here would quietly break anyone who later enables the OpenNext caching
 * that depends on them.
 *
 * Excluded from tsconfig.json: it imports a build artefact that does not exist
 * on a clean checkout, so type-checking it would fail before the first build.
 * That exclusion is why this file holds no logic. Everything the cron does
 * lives in src/lib/newsroom/scheduled.ts, where the compiler can see it.
 */
import openNextWorker from "../.open-next/worker.js";
import { runScheduledDiscovery, describeOutcome } from "../src/lib/newsroom/scheduled";

export * from "../.open-next/worker.js";
export { RateLimiterDO } from "./rate-limiter-do";

const worker = {
  ...openNextWorker,

  /**
   * Newsroom discovery, on a schedule.
   *
   * Calls the discovery service directly. It does not make an HTTP request to
   * the application's own routes: there is no public endpoint for this, and
   * therefore no shared secret to manage or leak.
   *
   * `runScheduledDiscovery` never throws — it reports. A cron handler that
   * throws produces a retry and a log line nobody reads, whereas a failed run
   * is already recorded in newsroom_pipeline_runs and visible in the Editorial
   * Inbox.
   */
  async scheduled(_event: ScheduledController, env: { DB?: unknown }, ctx: ExecutionContext) {
    const work = runScheduledDiscovery(env as Parameters<typeof runScheduledDiscovery>[0]).then(
      (outcome) => {
        console.log(describeOutcome(outcome));
      }
    );

    // waitUntil so the run is not cut short when scheduled() returns, and
    // awaited so a cron invocation that finishes early does not look
    // successful while the work is still in flight.
    ctx.waitUntil(work);
    await work;
  },
};

export default worker;
