/**
 * The Worker entry point.
 *
 * A Durable Object class has to be exported from the same script Wrangler
 * deploys, and `.open-next/worker.js` is generated by `opennextjs-cloudflare
 * build` on every run — editing it would be overwritten immediately. So
 * wrangler.jsonc points `main` here instead, and this file re-exports the
 * generated Worker unchanged and adds the one class OpenNext knows nothing
 * about.
 *
 * `export *` does not carry a default export, which is why the default is
 * re-exported on its own line. The wildcard matters too: OpenNext exports its
 * own Durable Objects (DOQueueHandler, DOShardedTagCache, BucketCachePurge),
 * and dropping them here would quietly break anyone who later enables the
 * OpenNext caching that depends on them.
 *
 * Excluded from tsconfig.json: it imports a build artefact that does not exist
 * on a clean checkout, so type-checking it would fail before the first build.
 */
export * from "../.open-next/worker.js";
export { default } from "../.open-next/worker.js";

export { RateLimiterDO } from "./rate-limiter-do";
