/**
 * Print the SQL that creates (or resets) the editorial admin account.
 *
 * On Node the account is created at boot from STAI_ADMIN_EMAIL /
 * STAI_ADMIN_PASSWORD. A Worker must not do that: writing to the production
 * database as a side effect of a deploy is exactly the class of behaviour the
 * seeding rules exist to prevent, and a Worker boots on every cold isolate,
 * not once.
 *
 * So on Cloudflare this is a deliberate, one-off operator action:
 *
 *   node scripts/admin-sql.mjs desk@example.com 'a-long-password' > /tmp/admin.sql
 *   npx wrangler d1 execute stai --local --file=/tmp/admin.sql
 *
 * The password is hashed here, so the plaintext never reaches the database,
 * the SQL file, or Cloudflare. Write the file somewhere temporary and delete
 * it afterwards; the hash is not a secret but the command line may be.
 *
 * ON CONFLICT DO NOTHING: re-running never rewrites an existing account, and
 * in particular never resets a password that was changed.
 */
import bcrypt from "bcryptjs";

const [email, password] = process.argv.slice(2);

if (!email || !password) {
  console.error("usage: node scripts/admin-sql.mjs <email> <password>");
  process.exit(1);
}
if (password.length < 12) {
  console.error("refusing: the admin password must be at least 12 characters");
  process.exit(1);
}

const hash = bcrypt.hashSync(password, 10);
const esc = (s) => String(s).replace(/'/g, "''");

process.stdout.write(
  `-- STAI editorial admin. Generated by scripts/admin-sql.mjs; contains a
-- bcrypt hash, never a plaintext password. Delete this file after applying.
INSERT INTO users (email, password_hash, name, firm, role, plan)
VALUES ('${esc(email.toLowerCase().trim())}', '${esc(hash)}', 'The Desk', 'STAI', 'admin', 'free')
ON CONFLICT(email) DO NOTHING;
`
);
