/**
 * Mirror migrations/*.sql and seeds/*.sql into a TypeScript module.
 *
 * The .sql files are authoritative — Wrangler applies those directly to D1 in
 * production, and they are what a reviewer reads. But the Node path cannot
 * read them from disk at runtime: Next's standalone server chdir()s into
 * .next/standalone, which contains no migrations directory, so a fs.readdir
 * silently finds nothing and the app boots against an empty database.
 *
 * (That is the same failure mode as .next/static not being copied into the
 * standalone output. Anything outside the bundle has to be either copied
 * deliberately or embedded. Embedded is harder to get wrong.)
 *
 * tests/d1-migrations.test.mjs re-runs this generator and fails if the output
 * differs, so the mirror cannot drift from the source.
 *
 * Run: npm run sql:sync
 */
import fs from "fs";
import path from "path";

const ROOT = path.resolve(import.meta.dirname, "..");
const OUT = path.join(ROOT, "src/lib/schema/sql.generated.ts");

function collect(dir) {
  const full = path.join(ROOT, dir);
  if (!fs.existsSync(full)) return [];
  return fs
    .readdirSync(full)
    .filter((f) => f.endsWith(".sql"))
    .sort() // 0001_, 0002_, … — lexical order is application order
    .map((name) => ({ name, sql: fs.readFileSync(path.join(full, name), "utf8") }));
}

const migrations = collect("migrations");
const seeds = collect("seeds");

const emit = (files) =>
  files
    .map((f) => `  { name: ${JSON.stringify(f.name)}, sql: ${JSON.stringify(f.sql)} },`)
    .join("\n");

const body = `/**
 * GENERATED by scripts/sync-sql.mjs — do not edit.
 *
 * A byte-for-byte mirror of migrations/*.sql and seeds/*.sql, embedded so the
 * Node runtime can apply them from inside a bundle. The .sql files remain the
 * source of truth and are what Wrangler applies to D1.
 *
 * Regenerate with: npm run sql:sync
 */

export type SqlFile = { name: string; sql: string };

export const MIGRATIONS: SqlFile[] = [
${emit(migrations)}
];

export const SEEDS: SqlFile[] = [
${emit(seeds)}
];
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, body);

console.log("src/lib/schema/sql.generated.ts");
for (const m of migrations) console.log(`  migration ${m.name} (${m.sql.length} bytes)`);
for (const s of seeds) console.log(`  seed      ${s.name} (${s.sql.length} bytes)`);
