import { describe, it, expect } from "vitest";
import { renderNeutralDocument, scanForTells } from "./render.ts";

const FIRM_PAPER = `## 1. Process narrative

Orders are received by email and entered into the ERP by customer service. The price is
taken from the customer price list.

## 2. Risks

| Ref | Risk | Assertion |
| --- | --- | --- |
| 1 | Unauthorised price overrides | Accuracy |
| 2 | Deliveries not invoiced | Completeness |
`;

describe("variant A rendering", () => {
  const html = renderNeutralDocument(FIRM_PAPER, { documentLabel: "Document 2" });

  it("passes the firm's own paper through the same shell", () => {
    expect(html).toContain("<h2>1. Process narrative</h2>");
    expect(html).toContain("Document 2");
    expect(html).toContain("font:14px/1.55 Georgia,serif"); // the shared shell
  });

  it("renders pipe tables and drops the separator row", () => {
    expect(html).toContain("<th>Risk</th>");
    expect(html).toContain("<td>Unauthorised price overrides</td>");
    expect(html).not.toContain("---");
  });

  it("escapes content rather than trusting it", () => {
    expect(renderNeutralDocument("## <script>alert(1)</script>")).toContain("&lt;script&gt;");
  });
});

describe("blinding hygiene", () => {
  it("passes a clean working paper", () => {
    expect(scanForTells(renderNeutralDocument(FIRM_PAPER))).toEqual([]);
  });

  it("catches origin tells before raters ever see the document", () => {
    const why = scanForTells(
      renderNeutralDocument("## Narrative\n\nThis narrative was generated by an AI system with 90% confidence."),
    ).map((t) => t.why);
    expect(why).toContain("names AI");
    expect(why).toContain("says generated");
    expect(why).toContain("confidence language");
  });

  it("names the vendor only when the vendor is actually named", () => {
    const why = scanForTells(renderNeutralDocument("## Narrative\n\nDrafted with Claude.")).map((t) => t.why);
    expect(why).toContain("names the model or vendor");
  });

  it("does not fire on ordinary audit vocabulary", () => {
    // "model" appears legitimately: the IFRS 15 five-step model, the ECL model.
    const clean = renderNeutralDocument(
      "## Revenue recognition\n\nThe entity applies the IFRS 15 five-step model. The expected credit loss model is applied to receivables.",
    );
    expect(scanForTells(clean)).toEqual([]);
  });

  it("catches the hedging register that marks machine prose", () => {
    const tells = scanForTells(renderNeutralDocument("## Controls\n\nIt appears that the review may possibly operate monthly."));
    expect(tells.map((t) => t.why)).toContain("hedging register");
  });
});
