/**
 * Working-paper export: renders content as a print-ready memo in a new
 * window — reference block, prepared-by, sources — formatted like
 * documentation an auditor could file. Client-side only, zero dependencies;
 * the user prints to PDF with the browser.
 */

export type WorkingPaper = {
  kind: "ASK-STAI ANSWER" | "ADAPTED PROMPT";
  title: string;
  preparedFor?: string;
  body: string;
  sources?: { n: number; label: string; href: string }[];
  context?: { label: string; value: string }[];
};

function esc(s: string) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export function openWorkingPaper(wp: WorkingPaper) {
  const ref = `STAI-WP-${new Date().toISOString().slice(0, 10).replace(/-/g, "")}-${Math.random()
    .toString(36)
    .slice(2, 6)
    .toUpperCase()}`;
  const date = new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });

  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>${esc(wp.title)} — ${ref}</title>
<style>
  body { font-family: Georgia, 'Times New Roman', serif; color: #1a1a1a; margin: 3rem auto; max-width: 44rem; padding: 0 1.5rem; line-height: 1.55; }
  .head { border: 1.5px solid #1a1a1a; padding: 1rem 1.25rem; display: grid; grid-template-columns: 1fr 1fr; gap: .4rem 2rem; font-family: 'Courier New', monospace; font-size: .78rem; }
  .head b { text-transform: uppercase; letter-spacing: .06em; }
  h1 { font-size: 1.35rem; margin: 1.6rem 0 .4rem; }
  .kind { font-family: 'Courier New', monospace; font-size: .72rem; letter-spacing: .14em; }
  .ctx { margin: 1rem 0; font-size: .9rem; border-left: 3px solid #999; padding-left: 1rem; }
  .body { white-space: pre-wrap; font-size: .95rem; margin-top: 1.2rem; }
  .src { margin-top: 2rem; border-top: 1px solid #999; padding-top: .8rem; font-size: .82rem; }
  .src p { margin: .25rem 0; }
  .foot { margin-top: 2.5rem; font-family: 'Courier New', monospace; font-size: .7rem; color: #555; border-top: 1px solid #ccc; padding-top: .6rem; }
  @media print { .noprint { display: none; } body { margin: 0 auto; } }
</style></head><body>
<div class="head">
  <span><b>Reference</b><br>${ref}</span>
  <span><b>Date prepared</b><br>${date}</span>
  <span><b>Source</b><br>STAI — stai.ai</span>
  <span><b>Type</b><br>${wp.kind}</span>
</div>
<p class="kind">${wp.kind} — FOR ENGAGEMENT FILE USE; PROFESSIONAL REVIEW REQUIRED BEFORE RELIANCE</p>
<h1>${esc(wp.title)}</h1>
${
  wp.context?.length
    ? `<div class="ctx">${wp.context.map((c) => `<div><b>${esc(c.label)}:</b> ${esc(c.value)}</div>`).join("")}</div>`
    : ""
}
<div class="body">${esc(wp.body)}</div>
${
  wp.sources?.length
    ? `<div class="src"><b>Sources</b>${wp.sources
        .map((s) => `<p>[${s.n}] ${esc(s.label)} — ${esc(s.href)}</p>`)
        .join("")}</div>`
    : ""
}
<div class="foot">Generated by STAI (stai.ai). AI-assisted content: verify against source material before filing. This document does not constitute professional advice.</div>
<p class="noprint"><button onclick="window.print()" style="font-family: monospace; padding: .5rem 1rem; margin-top: 1rem;">Print / save as PDF</button></p>
</body></html>`;

  const win = window.open("", "_blank", "noopener,width=880,height=1000");
  if (!win) return;
  win.document.write(html);
  win.document.close();
}
